version: '2'
services:
    serviceusergorilas-app:
        image: serviceusergorilas
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://serviceusergorilas-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=serviceUserGorilas
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    serviceusergorilas-mongodb:
        extends:
            file: mongodb.yml
            service: serviceusergorilas-mongodb
